package com.example.composeapp.ui.theme

import androidx.compose.ui.graphics.Color

val replyLightPrimary = Color(0xffF78361)
val replyLightOnPrimary = Color(0xFFFFFFFF)
val replyLightPrimaryContainer = Color(0xFFF54B64)
val replyLightOnPrimaryContainer = Color(0xFF40000D)
val replyLightSecondary = Color(0xFF9F4124)
val replyLightOnSecondary = Color(0xFFFFFFFF)
val replyLightSecondaryContainer = Color(0xFFFFDBD1)
val replyLightOnSecondaryContainer = Color(0xFF3B0A00)
val replyLightTertiary = Color(0xFF76592F)
val replyLightOnTertiary = Color(0xFFFFFFFF)
val replyLightTertiaryContainer = Color(0xFFFFDDB3)
val replyLightOnTertiaryContainer = Color(0xFF291800)
val replyLightError = Color(0xFFBA1A1A)
val replyLightErrorContainer = Color(0xFFFFDAD6)
val replyLightOnError = Color(0xFFFFFFFF)
val replyLightOnErrorContainer = Color(0xFF410002)
val replyLightBackground = Color(0xFFFFFBFF)
val replyLightOnBackground = Color(0xFF201A1A)
val replyLightSurface = Color(0xFFFFFBFF)
val replyLightOnSurface = Color(0xFF201A1A)
val replyLightSurfaceVariant = Color(0xFFF4DDDD)
val replyLightOnSurfaceVariant = Color(0xFF4E586E)      
val replyLightOutline = Color(0xFF857373)
val replyLightInverseOnSurface = Color(0xFFFBEEED)
val replyLightInverseSurface = Color(0xFF362F2F)
val replyLightPrimaryInverse = Color(0xFFFFB2B6)

val replyDarkPrimary = Color(0xFFF78361)
val replyDarkOnPrimary = Color(0xFF67001B)
val replyDarkPrimaryContainer = Color(0xFFF54B64)
val replyDarkOnPrimaryContainer = Color(0xFFFFDADB)
val replyDarkSecondary = Color(0xFFFFB5A0)
val replyDarkOnSecondary = Color(0xFF5F1500)
val replyDarkSecondaryContainer = Color(0xFF802A0F)
val replyDarkOnSecondaryContainer = Color(0xFFFFDBD1)
val replyDarkTertiary = Color(0xFFE7C08E)
val replyDarkOnTertiary = Color(0xFF432C06)
val replyDarkTertiaryContainer = Color(0xFF5C421A)
val replyDarkOnTertiaryContainer = Color(0xFFFFDDB3)
val replyDarkError = Color(0xFFFFB4AB)
val replyDarkErrorContainer = Color(0xFF93000A)
val replyDarkOnError = Color(0xFF690005)
val replyDarkOnErrorContainer = Color(0xFFFFDAD6)
val replyDarkBackground = Color(0xFF201A1A)
val replyDarkOnBackground = Color(0xFFECE0DF)
val replyDarkSurface = Color(0xFF201A1A)
val replyDarkOnSurface = Color(0xFFECE0DF)
val replyDarkSurfaceVariant = Color(0xFF524344)
val replyDarkOnSurfaceVariant = Color(0xFFD7C1C2)
val replyDarkOutline = Color(0xFF9F8C8C)
val replyDarkInverseOnSurface = Color(0xFF201A1A)
val replyDarkInverseSurface = Color(0xFFECE0DF)
val replyDarkPrimaryInverse = Color(0xFFB81A3C)