package com.example.composeapp.ui.theme

import androidx.compose.ui.graphics.Color

val replyLightPrimary = Color(0xff266c2b)
val replyLightOnPrimary = Color(0xFFFFFFFF)
val replyLightPrimaryContainer = Color(0xFFaaf5a3)
val replyLightOnPrimaryContainer = Color(0xFF002204)
val replyLightSecondary = Color(0xFF52634f)
val replyLightOnSecondary = Color(0xFFFFFFFF)
val replyLightSecondaryContainer = Color(0xFFd5e8cf)
val replyLightOnSecondaryContainer = Color(0xF111f0f)
val replyLightTertiary = Color(0xFF38656a)
val replyLightOnTertiary = Color(0xFFFFFFFF)
val replyLightTertiaryContainer = Color(0xFFbcebf0)
val replyLightOnTertiaryContainer = Color(0xFF002023)
val replyLightError = Color(0xFFba1a1a)
val replyLightErrorContainer = Color(0xFFffdad6)
val replyLightOnError = Color(0xFFFFFFFF)
val replyLightOnErrorContainer = Color(0xFF410002)
val replyLightBackground = Color(0xFFfcfdf6)
val replyLightOnBackground = Color(0xFF1F1B16)
val replyLightSurface = Color(0xFFfcfdf6)
val replyLightOnSurface = Color(0xFF1a1c19)
val replyLightSurfaceVariant = Color(0xFFdee5d8)
val replyLightOnSurfaceVariant = Color(0xFF424940)
val replyLightOutline = Color(0xFF72796)
val replyLightInverseOnSurface = Color(0xFFF9EFE6)
val replyLightInverseSurface = Color(0xFF34302A)
val replyLightPrimaryInverse = Color(0xFFFFB945)

val replyDarkPrimary = Color(0xFF8fd889)
val replyDarkOnPrimary = Color(0xFF00390a)
val replyDarkPrimaryContainer = Color(0xFF045315)
val replyDarkOnPrimaryContainer = Color(0xFFaaf5a3)
val replyDarkSecondary = Color(0xFFbaccb3)
val replyDarkOnSecondary = Color(0xFF253423)
val replyDarkSecondaryContainer = Color(0xFF3b4b38)
val replyDarkOnSecondaryContainer = Color(0xFFd5e8cf)
val replyDarkTertiary = Color(0xFFa0cfd4)
val replyDarkOnTertiary = Color(0xFF00363b)
val replyDarkTertiaryContainer = Color(0xFF1f4d52)
val replyDarkOnTertiaryContainer = Color(0xFFbcebf0)
val replyDarkError = Color(0xFFffb4ab)
val replyDarkErrorContainer = Color(0xFF690005)
val replyDarkOnError = Color(0xFF680003)
val replyDarkOnErrorContainer = Color(0xFFffdad6)
val replyDarkBackground = Color(0xFF1a1c19)
val replyDarkOnBackground = Color(0xFFe2e3dd)
val replyDarkSurface = Color(0xFF1a1c19)
val replyDarkOnSurface = Color(0xFFe2e3dd)
val replyDarkSurfaceVariant = Color(0xFF424940)
val replyDarkOnSurfaceVariant = Color(0xFFc2c9bd)
val replyDarkOutline = Color(0xFF8c9388)
val replyDarkInverseOnSurface = Color(0xFF32281A)
val replyDarkInverseSurface = Color(0xFFEAE1D9)
val replyDarkPrimaryInverse = Color(0xFF624000)